name: Build and Release

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip Folder
        run: zip -r ${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*" "node_modules/*" "tests/*" ".gitignore" ".distignore" ".editorconfig" ".phpcs.xml" "composer.json" "composer.lock" "package.json" "package-lock.json" ".vscode/*" "bin/*" "vendor" ".phpcs.xml.dist" ".phpunit.result.cache" ".travis.yml" "phpunit.xml.dist"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.repository.name }}.zip